config/routes.rb
Rails.application.routes.draw do
  get 'new_ship' => 'visitors#new_ship'
  get 'incident_occurred' => 'visitors#incident_occurred'
  get 'about' => 'visitors#about'
  root to: 'visitors#index'
  devise_for :users
end

app/models/chart.rb
require 'csv'

class Chart
  attr_reader :data, :filtered, :result
  def initialize
    csv = CSV.read(File.join(Rails.root, 'lib', 'assets','combined6.csv'), headers: true, header_converters: :symbol)
    @data = []
    csv.each do |row|
      @data << row.to_hash
    end
  end

  def averages_by_month(crane: 0, container: 0)
    filtered = data.select { |row| row[:range_of_tonnage] == "1K-5K" && row[:gross_vessel_throughput].to_f >= 1000.0 && row[:gross_vessel_throughput].to_f < 1300.0 && row[:incident__crane].to_i == crane && row[:incident__container].to_i == container }
    months = filtered.group_by_month { |row| row.fetch(:actual_berth) }
    averages = {}
    months.each do |k, v|
      # v is an array of hashes
      hours = v.map{ |r| r[:gross_hour].to_f }
      values = {
        records: hours.size,
        average_hours: hours.inject(:+) / v.size.to_f,
        min: hours.min,
        max: hours.max
      }
      averages[k] = values
    end
    @result = averages
  end

  def average_hours_ary
    ary = []
    @result.each do |k, v|
      # v is a hash
      ary << [k.to_f * 1000, v[:average_hours].round(1)]
    end
    ary
  end

  def ranges_ary
    ary = []
    @result.each do |k, v|
      # v is a hash
      ary << [k.to_f * 1000, v[:min].round(1), v[:max].round(1)]
    end
    ary
  end

  def main_average
    ary = []
    main_ave = @result.map{ |r, v| v[:average_hours] }.inject(:+) / @result.size
    ary << [@result.keys.first.to_f * 1000, main_ave.round(1)]
    ary << [@result.keys.last.to_f * 1000, main_ave.round(1)]
  end

  def records
    records = @result.map{ |r, v| v[:records] }.inject(:+)
  end
end

# {:vessel_call_cd=>"1500000279",
#  :vessel_record_id=>"53626",
#  :cargo_client_code_cd=>"Cargo Client Code E",
#  :berth_nbr=>"J4A/4",
#  :actual_berth=>"17/2/2015 18:10",
#  :actual_unberth=>"18/2/2015 12:30",
#  :first_activity=>"17/2/2015 19:00",
#  :last_activity=>"18/2/2015 12:00",
#  :gross_hour=>"18.33",
#  :rain_hours=>"0",
#  :gross_vessel_throughput=>"10490.05",
#  :first_cargo=>"18/2/2015 12:00",
#  :last_cargo=>"18/2/2015 7:45",
#  :range_of_tonnage=>">10K",
#  :throughput_per_hour=>"572",
#  :incident__crane=>"0",
#  :incident__container=>"0"}

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
    chart = Chart.new 
    @averages = chart.averages_by_month(crane: 0, container: 0)
    gon.ranges = chart.ranges_ary
    gon.average_hours = chart.average_hours_ary
    gon.main_average = chart.main_average
    gon.records = chart.records
    @incident_1 = chart.averages_by_month(crane: 0, container: 1)
    gon.ranges1 = chart.ranges_ary
    gon.average_hours1 = chart.average_hours_ary
    gon.main_average1 = chart.main_average
    gon.records1 = chart.records
    @incident_2 = chart.averages_by_month(crane: 1, container: 1)
    gon.ranges2 = chart.ranges_ary
    gon.average_hours2 = chart.average_hours_ary
    gon.main_average2 = chart.main_average
    gon.records2 = chart.records
  end

  def incident_occurred
    chart = Chart.new 
    @averages = chart.averages_by_month(crane: 0, container: 1)
    gon.ranges = chart.ranges_ary
    gon.average_hours = chart.average_hours_ary
    gon.main_average = chart.main_average
  end

  def new_ship
    
  end

  def about
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-default.navbar-static-top
  .navbar-header
    button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
      span.sr-only Toggle navigation
      span.icon-bar
      span.icon-bar
      span.icon-bar
    = link_to 'Mainstreet Demo', root_path, class: 'navbar-brand'
  .collapse.navbar-collapse
    ul.nav.navbar-nav
      == render 'layouts/navigation_links'
  ul.nav.navbar-top-links.navbar-right
    li.dropdown
      a.dropdown-toggle[data-toggle="dropdown" href="#"]
        i.fa.fa-envelope.fa-fw
        i.fa.fa-caret-down
      ul.dropdown-menu.dropdown-messages
        li
          a[href="#"]

            div
              strong
                | John Smith
              span.pull-right.text-muted
                em
                  | Yesterday
            div
              | Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...
        li.divider
        li
          a[href="#"]

            div
              strong
                | John Smith
              span.pull-right.text-muted
                em
                  | Yesterday
            div
              | Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...
        li.divider
        li
          a[href="#"]

            div
              strong
                | John Smith
              span.pull-right.text-muted
                em
                  | Yesterday
            div
              | Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...
        li.divider
        li
          a.text-center[href="#"]
            strong
              | Read All Messages
            i.fa.fa-angle-right
    li.dropdown
      a.dropdown-toggle[data-toggle="dropdown" href="#"]
        i.fa.fa-tasks.fa-fw
        i.fa.fa-caret-down
      ul.dropdown-menu.dropdown-tasks
        li
          a[href="#"]

            div
              p
                strong
                  | Task 1
                span.pull-right.text-muted
                  | 40% Complete
              .progress.progress-striped.active
                .progress-bar.progress-bar-success[role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%"]
                  span.sr-only
                    | 40% Complete (success)
        li.divider
        li
          a[href="#"]

            div
              p
                strong
                  | Task 2
                span.pull-right.text-muted
                  | 20% Complete
              .progress.progress-striped.active
                .progress-bar.progress-bar-info[role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%"]
                  span.sr-only
                    | 20% Complete
        li.divider
        li
          a[href="#"]

            div
              p
                strong
                  | Task 3
                span.pull-right.text-muted
                  | 60% Complete
              .progress.progress-striped.active
                .progress-bar.progress-bar-warning[role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%"]
                  span.sr-only
                    | 60% Complete (warning)
        li.divider
        li
          a[href="#"]

            div
              p
                strong
                  | Task 4
                span.pull-right.text-muted
                  | 80% Complete
              .progress.progress-striped.active
                .progress-bar.progress-bar-danger[role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%"]
                  span.sr-only
                    | 80% Complete (danger)
        li.divider
        li
          a.text-center[href="#"]
            strong
              | See All Tasks
            i.fa.fa-angle-right
    li.dropdown
      a.dropdown-toggle[data-toggle="dropdown" href="#"]
        i.fa.fa-bell.fa-fw
        i.fa.fa-caret-down
      ul.dropdown-menu.dropdown-alerts
        li
          a[href="#"]

            div
              i.fa.fa-comment.fa-fw
              |  New Comment 
              span.pull-right.text-muted.small
                | 4 minutes ago
        li.divider
        li
          a[href="#"]

            div
              i.fa.fa-twitter.fa-fw
              |  3 New Followers 
              span.pull-right.text-muted.small
                | 12 minutes ago
        li.divider
        li
          a[href="#"]

            div
              i.fa.fa-envelope.fa-fw
              |  Message Sent 
              span.pull-right.text-muted.small
                | 4 minutes ago
        li.divider
        li
          a[href="#"]

            div
              i.fa.fa-tasks.fa-fw
              |  New Task 
              span.pull-right.text-muted.small
                | 4 minutes ago
        li.divider
        li
          a[href="#"]

            div
              i.fa.fa-upload.fa-fw
              |  Server Rebooted 
              span.pull-right.text-muted.small
                | 4 minutes ago
        li.divider
        li
          a.text-center[href="#"]
            strong
              | See All Alerts
            i.fa.fa-angle-right
    li.dropdown
      a.dropdown-toggle[data-toggle="dropdown" href="#"]
        i.fa.fa-user.fa-fw
        i.fa.fa-caret-down
      ul.dropdown-menu.dropdown-user
        li
          a[href="#"]
            i.fa.fa-user.fa-fw
            |  User Profile
        li
          a[href="#"]
            i.fa.fa-gear.fa-fw
            |  Settings
        li.divider
        li
          a[href="login.html"]
            i.fa.fa-sign-out.fa-fw
            |  Logout
  .navbar-default.sidebar[role="navigation"]
    .sidebar-nav.navbar-collapse
      ul#side-menu.nav
        li.sidebar-search
          .input-group.custom-search-form
            input.form-control[type="text" placeholder="Search..."]
            span.input-group-btn
              button.btn.btn-default[type="button"]
                i.fa.fa-search
        li
          a[href="#{new_ship_path}"]
            i.fa.fa-ship.fa-fw
            |  New Ship
          a[href="#{root_path}"]
            i.fa.fa-dashboard.fa-fw
            |  Dashboard

app/views/layouts/_navigation_links.html.slim
- # add navigation links to this file
li
  = link_to 'About', about_path
- if user_signed_in?
  li
    = link_to 'Edit account', edit_user_registration_path
  li
    = link_to 'Sign out', destroy_user_session_path, :method=>'delete'
- else
  li
    = link_to 'Sign in', new_user_session_path
  li
    = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Smartport'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Smartport'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == include_gon
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    #wrapper
      == render 'layouts/navigation'
      = yield
    / header
    /   == render 'layouts/navigation'
    / main[role="main"]
    /   == render 'layouts/messages'
    /   == yield

app/views/visitors/about.html.slim
- content_for :title do
  | About
.container 
  h3
    | About the Website
  p
    |  This web application was created with 
    = link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/')
    |  from the 
    = link_to('RailsApps project', 'http://railsapps.github.io/')
    | . 
  
  / h3 Users

  / - @users.each do |user|
  /   p= user.email

app/views/visitors/incident_occurred.html.slim
#page-wrapper
  .row
    .col-lg-12
      h1.page-header
        | T.O.R.V.S.
  .row
    .col-lg-3.col-md-6
      .panel.panel-primary
        .panel-heading
          .row
            .col-xs-3
              i.fa.fa-files-o.fa-5x
            .col-xs-9.text-right
              .huge
                | 168
              div
                | Records with similar attributes

    .col-lg-3.col-md-6
      .panel.panel-green
        .panel-heading
          .row
            .col-xs-3
              i.fa.fa-tasks.fa-5x
            .col-xs-9.text-right
              .huge
                | 0
              div
                | Incidents 

    .col-lg-3.col-md-6
      .panel.panel-yellow
        .panel-heading
          .row
            .col-xs-3
              i.fa.fa-ship.fa-5x
            .col-xs-9.text-right
              .huge
                | 10h 0min
              div
                | Expected Unberthing Time

    .col-lg-3.col-md-6
      #panel-delay.panel.panel-red
        .panel-heading
          .row
            .col-xs-3
              i.fa.fa-support.fa-5x
            .col-xs-9.text-right
              .huge
                | 5h
              div
                | Delay

  .row
    .col-lg-8
      .panel.panel-default
        .panel-heading
          i.fa.fa-bar-chart-o.fa-fw
          | Past Ship Data
          .pull-right
            .btn-group
              button.btn.btn-default.btn-xs.dropdown-toggle[type="button" data-toggle="dropdown"]
                |  Actions 
                span.caret
              ul.dropdown-menu.pull-right[role="menu"]
                li
                  a[href="#"]
                    | Action
                li
                  a[href="#"]
                    | Another action
                li
                  a[href="#"]
                    | Something else here
                li.divider
                li
                  a[href="#"]
                    | Separated link
        .panel-body
          #chart
      .panel.panel-default
        .panel-heading
          i.fa.fa-bar-chart-o.fa-fw
          |  Event Reporting
          .pull-right
            .btn-group
              button.btn.btn-default.btn-xs.dropdown-toggle[type="button" data-toggle="dropdown"]
                |  Actions 
                span.caret
              ul.dropdown-menu.pull-right[role="menu"]
                li
                  a[href="#"]
                    | Action
                li
                  a[href="#"]
                    | Another action
                li
                  a[href="#"]
                    | Something else here
                li.divider
                li
                  a[href="#"]
                    | Separated link
        .panel-body
          .row
            .col-lg-6
              h4 Events
              .checkbox
                label
                  input#action1[type="checkbox"]
                  | First Activity
                p.show1.alert.alert-warning Average First Activity start time is 30 minutes ago. Expected Delay: 30 minutes
              .checkbox
                label
                  input[type="checkbox" disabled]
                  | First Cargo Loaded
              .checkbox
                label
                  input[type="checkbox" disabled]
                  | Last Cargo Unloaded
              .checkbox
                label
                  input[type="checkbox" disabled]
                  | Last Activity
            .col-lg-6
              h4 Incidents
              p
                button#action2.btn.btn-danger Crane Breakdown
              p
                button.btn.btn-danger Container Damage
              p
                button.btn.btn-danger Ship Malfunction
              p
                button.btn.btn-danger Bunker Supply Delay
              p
                button.btn.btn-danger Negative Connectivity


    .col-lg-4
      .panel.panel-default
        .panel-heading
          i.fa.fa-bell.fa-fw
          |  Notifications Panel 
        .panel-body
          .list-group
            / a.list-group-item[href="#"]
            /   i.fa.fa-comment.fa-fw
            /   |  New Comment 
            /   span.pull-right.text-muted.small
            /     em
            /       | 4 minutes ago
            / a.list-group-item[href="#"]
            /   i.fa.fa-twitter.fa-fw
            /   |  3 New Followers 
            /   span.pull-right.text-muted.small
            /     em
            /       | 12 minutes ago
            / a.list-group-item[href="#"]
            /   i.fa.fa-envelope.fa-fw
            /   |  Message Sent 
            /   span.pull-right.text-muted.small
            /     em
            /       | 27 minutes ago
            / a.list-group-item[href="#"]
            /   i.fa.fa-tasks.fa-fw
            /   |  New Task 
            /   span.pull-right.text-muted.small
            /     em
            /       | 43 minutes ago
            / a.list-group-item[href="#"]
            /   i.fa.fa-upload.fa-fw
            /   |  Server Rebooted 
            /   span.pull-right.text-muted.small
            /     em
            /       | 11:32 AM
            / a.list-group-item[href="#"]
            /   i.fa.fa-bolt.fa-fw
            /   |  Server Crashed! 
            /   span.pull-right.text-muted.small
            /     em
            /       | 11:13 AM
            / a.list-group-item[href="#"]
            /   i.fa.fa-warning.fa-fw
            /   |  Server Not Responding 
            /   span.pull-right.text-muted.small
            /     em
            /       | 10:57 AM
            a.list-group-item.show1[href="#"]
              i.fa.fa-shopping-cart.fa-fw
              |  First Activity - Delayed by 30min
              span.pull-right.text-muted.small
                em
                  | 5 minutes ago
            a.list-group-item[href="#"]
              i.fa.fa-ship.fa-fw
              |  New Shipment created 
              span.pull-right.text-muted.small
                em
                  | 1 hour ago
          a.btn.btn-default.btn-block[href="#"]
            | View All Alerts
      .chat-panel.panel.panel-default
        .panel-heading
          i.fa.fa-comments.fa-fw
          |  Chat 
          .btn-group.pull-right
            button.btn.btn-default.btn-xs.dropdown-toggle[type="button" data-toggle="dropdown"]
              i.fa.fa-chevron-down
            ul.dropdown-menu.slidedown
              li
                a[href="#"]
                  i.fa.fa-refresh.fa-fw
                  |  Refresh 
              li
                a[href="#"]
                  i.fa.fa-check-circle.fa-fw
                  |  Available 
              li
                a[href="#"]
                  i.fa.fa-times.fa-fw
                  |  Busy 
              li
                a[href="#"]
                  i.fa.fa-clock-o.fa-fw
                  |  Away 
              li.divider
              li
                a[href="#"]
                  i.fa.fa-sign-out.fa-fw
                  |  Sign Out 
        .panel-body
          ul.chat
            li.left.clearfix
              span.chat-img.pull-left
                img.img-circle[src="http://placehold.it/50/55C1E7/fff" alt="User Avatar"]
              .chat-body.clearfix
                .header
                  strong.primary-font
                    | Jack Sparrow
                  small.pull-right.text-muted
                    i.fa.fa-clock-o.fa-fw
                    |  12 mins ago 
                p
                  |  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales. 
            li.right.clearfix
              span.chat-img.pull-right
                img.img-circle[src="http://placehold.it/50/FA6F57/fff" alt="User Avatar"]
              .chat-body.clearfix
                .header
                  small.text-muted
                    i.fa.fa-clock-o.fa-fw
                    |  13 mins ago
                  strong.pull-right.primary-font
                    | Terminal Controller
                p
                  |  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales. 
            li.left.clearfix
              span.chat-img.pull-left
                img.img-circle[src="http://placehold.it/50/55C1E7/fff" alt="User Avatar"]
              .chat-body.clearfix
                .header
                  strong.primary-font
                    | Jack Sparrow
                  small.pull-right.text-muted
                    i.fa.fa-clock-o.fa-fw
                    |  14 mins ago
                p
                  |  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales. 
            li.right.clearfix
              span.chat-img.pull-right
                img.img-circle[src="http://placehold.it/50/FA6F57/fff" alt="User Avatar"]
              .chat-body.clearfix
                .header
                  small.text-muted
                    i.fa.fa-clock-o.fa-fw
                    |  15 mins ago
                  strong.pull-right.primary-font
                    | Bhaumik Patel
                p
                  |  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales. 
        .panel-footer
          .input-group
            input#btn-input.form-control.input-sm[type="text" placeholder="Type your message here..."]
            span.input-group-btn
              button#btn-chat.btn.btn-warning.btn-sm
                |  Send 

app/views/visitors/new_ship.html.slim
#page-wrapper
  .row
    .col-lg-12
      h1.page-header
        | New Shipment
  .row
    .col-lg-12
      .panel.panel-default
        .panel-heading
          | This is the starting point for every ship that comes in to berth.
        .panel-body
          .row
            .col-lg-6
              form[role="form" method="GET" action="#{root_path}"]
                .form-group
                  label
                    | Throughput
                  input.form-control[name="throughput" placeholder="1100"]
                  p.help-block
                    | Total cargo to be loaded and unloaded (TEUs)

                .form-group
                  label
                    | Tonnage
                  select.form-control[name="tonnage"]
                    option
                      | 1K-5K
                    option
                      | 5K-10K
                    option
                      | >10K
                .form-group
                  label
                    | Number of cranes
                  input.form-control[name="cranes" placeholder="3"]
                  p.help-block
                    | No. of cranes deployed to the ship
                button.btn.btn-primary[type="submit"]
                  | Next